[app]
title = "Stock Price Predictor"
sidebar_title = "Model Configuration"
default_ticker = "MSFT"  
start_date = "2015-01-01"  
end_date = "2024-06-05"  
future_date_default = "2024-06-10"  

[model]
look_back = 30  
lstm_units = 50  
epochs = 100  
batch_size = 64  
optimizer = "adam"  
loss_function = "mean_squared_error" 

[data]
ticker_source_url = "https://www.google.com/finance/"  
data_save_path = "./data"  
model_save_path = "./saved_model/stock_price_predictor.keras"  

[visualization]
figure_size = [16, 8]
line_colors = {actual="blue", train="green", test="red"}  
